POST  http://localhost:5000/auth/signin
Content-Type: application/json

{
    "username":"muneeb",
    "password":"muneeb"
}
###
GET     http://localhost:5000/products
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmIwZWJiYmViZmQxMjExNzM2NDZjNyIsImNhcnQiOltdLCJpYXQiOjE2NDc1MjM1MjgsImV4cCI6MTY0NzYwOTkyOH0.IJLKqS_FPtE7Qr__UblYhRZzl43rDSxSIPnFqu7b7Nk

###
POST     http://localhost:5000/cart/62331810c42c25959ad99c02
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmIwZWJiYmViZmQxMjExNzM2NDZjNyIsImNhcnQiOltdLCJpYXQiOjE2NDc1MjUxMDksImV4cCI6MTY0NzYxMTUwOX0.aV8-6xdfMvxRhoTZ8Z7cS3NbuKaxYkUQXKVexgdLfts