POST  http://localhost:5000/auth/signin
Content-Type: application/json

{
    "username":"muneeb",
    "password":"muneeb"
}
###
GET     http://localhost:5000/cart/
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjJiMGViYmJlYmZkMTIxMTczNjQ2YzciLCJ1c2VybmFtZSI6Im11bmVlYiIsImVtYWlsIjoibXVuZWViQGdtYWlsLmNvbSIsImNhcnQiOlt7Il9pZCI6IjYyMjlhYTRmNDhlY2NlMzdiZWE3YmVjOCIsIm5hbWUiOiJCYXJyYWdlIiwiZGVzY3JpcHRpb24iOiJUaGUgYXRtb3MgeCBOaWtlIEFpciBCYXJyYWdlIE1pZCDigJxQb3AgVGhlIFN0cmVldOKAnSBpcyBhIHZpYnJhbnQgcmVuZGl0aW9uIG9mIHRoZSBzaWxob3VldHRlIGJ5IEphcGFuZXNlIHJldGFpbGVyIGF0bW9zIGl0IHRha2VzIGluc3BpcmF0aW9uIGZyb20gSmFwYW5lc2UgcG9wIGN1bHR1cmUiLCJwcmljZSI6IjI1MDAiLCJpbWciOiJodHRwczovL2kucG9zdGltZy5jYy9xTUJOWkpMeS83NDUzMzM4Ny0xNzEzMzk0OTcyNjY2ODktMTk0MjkwOTYxMjU4NzE1MDUyMi1uLmpwZyIsImJyYW5kIjoiTmlrZSIsInNpemUiOiIxMSIsIl9fdiI6MCwicXR5IjpudWxsfV0sImlhdCI6MTY0NzQzODQ5NCwiZXhwIjoxNjQ3NTI0ODk0fQ.SJODmJSz4Wvj-UGgXF5nrJdLulA613_IQKlZb_OPzCI

###
GET http://localhost:5000/products